### ISSUE TITLE
Android Postfix Completion threw an uncaught NoClassDefFoundError.

### ISSUE THREAD

**Issue by Langthron** [takahirom/android-postfix-plugin#11]
when i used R.id.viewid.find+Tab
Android Postfix Completion threw an uncaught NoClassDefFoundError.
android studio 2.1.3

**Comment by takahirom** [comment]
You can use Android Studio 2.2 or 2.3, and probably It not cause NoClassDefFoundError

**Comment by albka1986** [comment]
I have the same problem. 
I use Android Studio ver. 3.0.1
Can you help?  If you need additional info, I will provide you.
