### ISSUE TITLE
Limit of characters in the Log.d

### ISSUE THREAD

**Issue by lolobosse** [takahirom/android-postfix-plugin#2]
Hi there,

First of all, I have to say that I'm a big fan of this plugin :smile: :+1: but I found a quite annoying issue, this plugin takes as TAG the name of the class but it's unable to detect that a class name is bigger than 23 characters which creates errors and you have to delete manually a part of the TAG in order to have a working TAG.

I think this issue could be easily fixed by removing all characters after the 23th one. Unhapilly, I do not have that much time to understand your code and modify it in order to get it to work :unamused: .

Best,

**Comment by takahirom** [comment]
Thank you for using the plugin. And Thank you for the report.
I has released the 1.1.6. Its features have been included in the release.

**Comment by lolobosse** [comment]
Pretty cool and fast ! Great plugin!
Just tested it and it works! Thanks a lot (you save me ~ 5 minutes per day with this update!)
