### ISSUE TITLE
any plan to make a .ifelse completion?

### ISSUE THREAD

**Issue by tedzyc** [takahirom/android-postfix-plugin#8]
I found that android-studio has .if and .else completion, but no .ifelse completion like:
condition.ifelse cast to:
if(condition) {

} else {

}
hope u can make this convenience:)

**Comment by takahirom** [comment]
Thanks!
But.. This plugin provides **android** postfix completion.
Probably you have to post it IntelliJ support.
https://intellij-support.jetbrains.com/hc/en-us/requests/new

**Comment by tedzyc** [comment]
Expect JetBrain will support it later.
